# Generated by Django 4.1.3 on 2022-11-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "first_name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("last_name", models.CharField(max_length=30)),
                ("phone", models.BigIntegerField()),
            ],
        ),
    ]
